// Maintains the live preview index. Zero dependencies, Node built-ins only.
//
//   node preview-index.mjs upsert <manifest> <branch> <url> <sha> <updated>
//   node preview-index.mjs remove <manifest> <branch>
//   node preview-index.mjs render <manifest> <readme>
//
// The manifest is a JSON array of { branch, url, sha, updated }. render writes a
// table between the PREVIEWS markers in the README, appending it at the end if
// the markers are not present.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const START = '<!-- PREVIEWS:START -->';
const END = '<!-- PREVIEWS:END -->';

const load = (p) => (existsSync(p) ? JSON.parse(readFileSync(p, 'utf8') || '[]') : []);
const save = (p, d) => writeFileSync(p, JSON.stringify(d, null, 2) + '\n');

// master first, then alphabetical.
const order = (a, b) =>
  a.branch === b.branch ? 0
    : a.branch === 'master' ? -1
    : b.branch === 'master' ? 1
    : a.branch.localeCompare(b.branch);

const [cmd, ...rest] = process.argv.slice(2);

if (cmd === 'upsert') {
  const [manifest, branch, url, sha, updated] = rest;
  const list = load(manifest);
  // Idempotency: keep the existing timestamp when the commit has not changed,
  // so re-running with the same state produces an identical manifest and no
  // diff. This makes the index self terminating, a loop cannot sustain itself.
  const prev = list.find((e) => e.branch === branch);
  const stamp = prev && prev.sha === sha ? prev.updated : updated;
  const next = list.filter((e) => e.branch !== branch);
  next.push({ branch, url, sha, updated: stamp });
  next.sort(order);
  save(manifest, next);
} else if (cmd === 'remove') {
  const [manifest, branch] = rest;
  save(manifest, load(manifest).filter((e) => e.branch !== branch));
} else if (cmd === 'render') {
  const [manifest, readme] = rest;
  const list = load(manifest).sort(order);

  const block = [
    START,
    '## Live previews',
    '',
    'Auto generated by the Branch previews workflow. Do not edit by hand.',
    '',
    ...(list.length
      ? [
          '| Branch | Preview | Updated (UTC) | Commit |',
          '| --- | --- | --- | --- |',
          ...list.map(
            (e) => `| \`${e.branch}\` | [open](${e.url}) | ${e.updated} | \`${e.sha}\` |`,
          ),
        ]
      : ['_No previews are currently deployed._']),
    END,
  ].join('\n');

  let md = readFileSync(readme, 'utf8');
  if (md.includes(START) && md.includes(END)) {
    md = md.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block);
  } else {
    md = md.replace(/\s*$/, '') + '\n\n' + block + '\n';
  }
  writeFileSync(readme, md);
} else {
  console.error(`unknown command: ${cmd}`);
  process.exit(1);
}
